#!/bin/bash -euo pipefail

export AWS_REGION="us-west-2"
export AWS_DEFAULT_REGION="${AWS_REGION}"
export AWS_PROFILE="sandbox" # "mlops-club"

THIS_DIR="$(dirname "${BASH_SOURCE[0]}")"

function cdk-deploy {
    cdk deploy \
        --app "uv run $THIS_DIR/infra.py" \
        --profile "$AWS_PROFILE" \
        --region "$AWS_REGION" \
        --outputs-file "$THIS_DIR/stack-outputs.json"
}


function fetch-ssh-key {
    # delete the key first
    chmod 777 "$THIS_DIR/ssh-key" 2>/dev/null || true
    rm -rf "$THIS_DIR/ssh-key" || true
    mkdir -p "$THIS_DIR/ssh-key"

    # get the key pair id from the key pair name
    local kp_id
    kp_id=$(aws ec2 describe-key-pairs \
        --key-names "cluster-keypair" \
        --query 'KeyPairs[0].KeyPairId' \
        --output text \
        --profile "$AWS_PROFILE" \
        --region "$AWS_REGION") || return 1

    # Overwrite the ssh key using the key pair id
    local param_path="/ec2/keypair/${kp_id}"
    if ! aws ssm get-parameter \
        --name "$param_path" --with-decryption \
        --query "Parameter.Value" --output text \
        --profile "$AWS_PROFILE" \
        --region "$AWS_REGION" > "$THIS_DIR/ssh-key/private-key.pem"; then
    echo "Parameter not found: $param_path" >&2
    return 2
    fi

    chmod 400 "$THIS_DIR/ssh-key/private-key.pem"
}

# ./run connect-to-instance <index>
# Connects to the EC2 instance at the given index (starts at 0)
function connect-to-instance {
    local index="${1:-0}"
    local public_ip=$(aws cloudformation describe-stacks \
        --stack-name cluster \
        --profile "$AWS_PROFILE" \
        --region "$AWS_REGION" \
        --output json | jq -r ".Stacks[0].Outputs[]? | select(.OutputKey==\"Instance${index}PublicIP\") | .OutputValue")
    
    if [ -z "$public_ip" ] || [ "$public_ip" = "null" ]; then
        echo "No public IP found for instance $index"
        return 1
    fi
    
    ssh -i "$THIS_DIR/ssh-key/private-key.pem" "ec2-user@${public_ip}"
}

function cdk-destroy {
    cdk destroy \
        --app "uv run $THIS_DIR/infra.py" \
        --profile "$AWS_PROFILE" \
        --region "$AWS_REGION"
}

function cdk-bootstrap {
    AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text --profile "$AWS_PROFILE")
    cdk bootstrap "aws://$AWS_ACCOUNT_ID/$AWS_REGION" --profile "$AWS_PROFILE"
}

function set-up-passwordless-ssh {
    # generate a new ssh key
    # ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N ""
    # copy it to each of the nodes
    for node in {1..3}; do
        ssh-copy-id -i "${HOME}/.ssh/id_ed25519.pub" "main@cluster-node-$node"
    done
}

function all {
    local cmd="$@"
    for node in {1..3}; do
        ssh "main@cluster-node-$node" "$cmd"
    done
}


function help {
    echo "Usage: $0 <command>"
    echo "Commands:"
    echo "  default - Run the default command"
    echo "  help - Show this help message"
}

time ${@:-help}